{% set name = "gwvet" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "b0a42c1e2ce0d1ba4941e56e92144aad707fc7a7d6a2b71eeb280f70f570f5c4"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - astropy >=1.2.1
    - decorator
    - dqsegdb
    - gwdetchar >=1.0.0
    - gwpy >=1.0.0
    - gwsumm >=1.0.1
    - gwtrigfind
    - lscsoft-glue >=1.60.0
    - markuppy
    - matplotlib-base >=2.0.0
    - numpy >=1.10
    - python >=3
    - scipy >=1.2.0

test:
  imports:
    - gwvet
    - gwvet.cli
    - gwvet.etg
    - gwvet.metric
    - gwvet.segments
    - gwvet.tabs
    - gwvet.triggers
  commands:
    # check scripts run ok
    - gwvet --help
    - gwvet-hug --help
    - gwvet-vdf --help

about:
  home: "https://github.com/gwpy/vet"
  doc_url: "https://github.com/gwpy/vet/blob/master/README.rst"
  dev_url: "https://github.com/gwpy/vet"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: "Gravitational-wave Veto Evaluation and Testing suite"
  description: |
    GWVET is an extension to the python toolbox GWSumm, used by the LIGO
    Scientific Collaboration to review and evaluate data-quality veto products

extra:
  recipe-maintainers:
    - alurban
